// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: controlplane.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Types of control-plane events
type ControlEventType int32

const (
	ControlEventType_CONTROL_EVENT_UNSPECIFIED ControlEventType = 0
	ControlEventType_CONTROL_EVENT_MIGRATE_OUT ControlEventType = 1
)

// Enum value maps for ControlEventType.
var (
	ControlEventType_name = map[int32]string{
		0: "CONTROL_EVENT_UNSPECIFIED",
		1: "CONTROL_EVENT_MIGRATE_OUT",
	}
	ControlEventType_value = map[string]int32{
		"CONTROL_EVENT_UNSPECIFIED": 0,
		"CONTROL_EVENT_MIGRATE_OUT": 1,
	}
)

func (x ControlEventType) Enum() *ControlEventType {
	p := new(ControlEventType)
	*p = x
	return p
}

func (x ControlEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_controlplane_proto_enumTypes[0].Descriptor()
}

func (ControlEventType) Type() protoreflect.EnumType {
	return &file_controlplane_proto_enumTypes[0]
}

func (x ControlEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlEventType.Descriptor instead.
func (ControlEventType) EnumDescriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{0}
}

type OpenControlStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      *ServerId              `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenControlStreamRequest) Reset() {
	*x = OpenControlStreamRequest{}
	mi := &file_controlplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenControlStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenControlStreamRequest) ProtoMessage() {}

func (x *OpenControlStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenControlStreamRequest.ProtoReflect.Descriptor instead.
func (*OpenControlStreamRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{0}
}

func (x *OpenControlStreamRequest) GetServerId() *ServerId {
	if x != nil {
		return x.ServerId
	}
	return nil
}

type ControlEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  ControlEventType       `protobuf:"varint,1,opt,name=type,proto3,enum=yggplane.v1.ControlEventType" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlEvent_MigrateOut
	Payload       isControlEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlEvent) Reset() {
	*x = ControlEvent{}
	mi := &file_controlplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlEvent) ProtoMessage() {}

func (x *ControlEvent) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlEvent.ProtoReflect.Descriptor instead.
func (*ControlEvent) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{1}
}

func (x *ControlEvent) GetType() ControlEventType {
	if x != nil {
		return x.Type
	}
	return ControlEventType_CONTROL_EVENT_UNSPECIFIED
}

func (x *ControlEvent) GetPayload() isControlEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlEvent) GetMigrateOut() *MigrateOutEvent {
	if x != nil {
		if x, ok := x.Payload.(*ControlEvent_MigrateOut); ok {
			return x.MigrateOut
		}
	}
	return nil
}

type isControlEvent_Payload interface {
	isControlEvent_Payload()
}

type ControlEvent_MigrateOut struct {
	MigrateOut *MigrateOutEvent `protobuf:"bytes,2,opt,name=migrate_out,json=migrateOut,proto3,oneof"`
}

func (*ControlEvent_MigrateOut) isControlEvent_Payload() {}

type MigrateOutEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      *PlayerId              `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	NewServer     *Server                `protobuf:"bytes,2,opt,name=new_server,json=newServer,proto3" json:"new_server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateOutEvent) Reset() {
	*x = MigrateOutEvent{}
	mi := &file_controlplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateOutEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateOutEvent) ProtoMessage() {}

func (x *MigrateOutEvent) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateOutEvent.ProtoReflect.Descriptor instead.
func (*MigrateOutEvent) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{2}
}

func (x *MigrateOutEvent) GetPlayerId() *PlayerId {
	if x != nil {
		return x.PlayerId
	}
	return nil
}

func (x *MigrateOutEvent) GetNewServer() *Server {
	if x != nil {
		return x.NewServer
	}
	return nil
}

// Generic acknowledgement for inbound operations
type ControlAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlAck) Reset() {
	*x = ControlAck{}
	mi := &file_controlplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlAck) ProtoMessage() {}

func (x *ControlAck) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlAck.ProtoReflect.Descriptor instead.
func (*ControlAck) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{3}
}

func (x *ControlAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ControlAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RegisterServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServerRequest) Reset() {
	*x = RegisterServerRequest{}
	mi := &file_controlplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServerRequest) ProtoMessage() {}

func (x *RegisterServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServerRequest.ProtoReflect.Descriptor instead.
func (*RegisterServerRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterServerRequest) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

type UnregisterServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      *ServerId              `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterServerRequest) Reset() {
	*x = UnregisterServerRequest{}
	mi := &file_controlplane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterServerRequest) ProtoMessage() {}

func (x *UnregisterServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterServerRequest.ProtoReflect.Descriptor instead.
func (*UnregisterServerRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{5}
}

func (x *UnregisterServerRequest) GetServerId() *ServerId {
	if x != nil {
		return x.ServerId
	}
	return nil
}

type AssignPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      *PlayerId              `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Position      *Position              `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignPlayerRequest) Reset() {
	*x = AssignPlayerRequest{}
	mi := &file_controlplane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPlayerRequest) ProtoMessage() {}

func (x *AssignPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPlayerRequest.ProtoReflect.Descriptor instead.
func (*AssignPlayerRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{6}
}

func (x *AssignPlayerRequest) GetPlayerId() *PlayerId {
	if x != nil {
		return x.PlayerId
	}
	return nil
}

func (x *AssignPlayerRequest) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type UpdatePlayerPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      *PlayerId              `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Position      *Position              `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlayerPositionRequest) Reset() {
	*x = UpdatePlayerPositionRequest{}
	mi := &file_controlplane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlayerPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerPositionRequest) ProtoMessage() {}

func (x *UpdatePlayerPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerPositionRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlayerPositionRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePlayerPositionRequest) GetPlayerId() *PlayerId {
	if x != nil {
		return x.PlayerId
	}
	return nil
}

func (x *UpdatePlayerPositionRequest) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type CompleteMigrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      *PlayerId              `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ServerId      *ServerId              `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteMigrationRequest) Reset() {
	*x = CompleteMigrationRequest{}
	mi := &file_controlplane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMigrationRequest) ProtoMessage() {}

func (x *CompleteMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMigrationRequest.ProtoReflect.Descriptor instead.
func (*CompleteMigrationRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{8}
}

func (x *CompleteMigrationRequest) GetPlayerId() *PlayerId {
	if x != nil {
		return x.PlayerId
	}
	return nil
}

func (x *CompleteMigrationRequest) GetServerId() *ServerId {
	if x != nil {
		return x.ServerId
	}
	return nil
}

var File_controlplane_proto protoreflect.FileDescriptor

const file_controlplane_proto_rawDesc = "" +
	"\n" +
	"\x12controlplane.proto\x12\vyggplane.v1\x1a\fcommon.proto\"N\n" +
	"\x18OpenControlStreamRequest\x122\n" +
	"\tserver_id\x18\x01 \x01(\v2\x15.yggplane.v1.ServerIdR\bserverId\"\x8d\x01\n" +
	"\fControlEvent\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.yggplane.v1.ControlEventTypeR\x04type\x12?\n" +
	"\vmigrate_out\x18\x02 \x01(\v2\x1c.yggplane.v1.MigrateOutEventH\x00R\n" +
	"migrateOutB\t\n" +
	"\apayload\"y\n" +
	"\x0fMigrateOutEvent\x122\n" +
	"\tplayer_id\x18\x01 \x01(\v2\x15.yggplane.v1.PlayerIdR\bplayerId\x122\n" +
	"\n" +
	"new_server\x18\x02 \x01(\v2\x13.yggplane.v1.ServerR\tnewServer\"6\n" +
	"\n" +
	"ControlAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"D\n" +
	"\x15RegisterServerRequest\x12+\n" +
	"\x06server\x18\x01 \x01(\v2\x13.yggplane.v1.ServerR\x06server\"M\n" +
	"\x17UnregisterServerRequest\x122\n" +
	"\tserver_id\x18\x01 \x01(\v2\x15.yggplane.v1.ServerIdR\bserverId\"|\n" +
	"\x13AssignPlayerRequest\x122\n" +
	"\tplayer_id\x18\x01 \x01(\v2\x15.yggplane.v1.PlayerIdR\bplayerId\x121\n" +
	"\bposition\x18\x02 \x01(\v2\x15.yggplane.v1.PositionR\bposition\"\x84\x01\n" +
	"\x1bUpdatePlayerPositionRequest\x122\n" +
	"\tplayer_id\x18\x01 \x01(\v2\x15.yggplane.v1.PlayerIdR\bplayerId\x121\n" +
	"\bposition\x18\x02 \x01(\v2\x15.yggplane.v1.PositionR\bposition\"\x82\x01\n" +
	"\x18CompleteMigrationRequest\x122\n" +
	"\tplayer_id\x18\x01 \x01(\v2\x15.yggplane.v1.PlayerIdR\bplayerId\x122\n" +
	"\tserver_id\x18\x02 \x01(\v2\x15.yggplane.v1.ServerIdR\bserverId*P\n" +
	"\x10ControlEventType\x12\x1d\n" +
	"\x19CONTROL_EVENT_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19CONTROL_EVENT_MIGRATE_OUT\x10\x012\x9a\x04\n" +
	"\x0eControlService\x12W\n" +
	"\x11OpenControlStream\x12%.yggplane.v1.OpenControlStreamRequest\x1a\x19.yggplane.v1.ControlEvent0\x01\x12Q\n" +
	"\x0eRegisterServer\x12\".yggplane.v1.RegisterServerRequest\x1a\x17.yggplane.v1.ControlAck(\x010\x01\x12U\n" +
	"\x10UnregisterServer\x12$.yggplane.v1.UnregisterServerRequest\x1a\x17.yggplane.v1.ControlAck(\x010\x01\x12M\n" +
	"\fAssignPlayer\x12 .yggplane.v1.AssignPlayerRequest\x1a\x17.yggplane.v1.ControlAck(\x010\x01\x12]\n" +
	"\x14UpdatePlayerPosition\x12(.yggplane.v1.UpdatePlayerPositionRequest\x1a\x17.yggplane.v1.ControlAck(\x010\x01\x12W\n" +
	"\x11CompleteMigration\x12%.yggplane.v1.CompleteMigrationRequest\x1a\x17.yggplane.v1.ControlAck(\x010\x01B-Z+github.com/didopimentel/yggdrasil/api/pb;pbb\x06proto3"

var (
	file_controlplane_proto_rawDescOnce sync.Once
	file_controlplane_proto_rawDescData []byte
)

func file_controlplane_proto_rawDescGZIP() []byte {
	file_controlplane_proto_rawDescOnce.Do(func() {
		file_controlplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_proto_rawDesc), len(file_controlplane_proto_rawDesc)))
	})
	return file_controlplane_proto_rawDescData
}

var file_controlplane_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_controlplane_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_controlplane_proto_goTypes = []any{
	(ControlEventType)(0),               // 0: yggplane.v1.ControlEventType
	(*OpenControlStreamRequest)(nil),    // 1: yggplane.v1.OpenControlStreamRequest
	(*ControlEvent)(nil),                // 2: yggplane.v1.ControlEvent
	(*MigrateOutEvent)(nil),             // 3: yggplane.v1.MigrateOutEvent
	(*ControlAck)(nil),                  // 4: yggplane.v1.ControlAck
	(*RegisterServerRequest)(nil),       // 5: yggplane.v1.RegisterServerRequest
	(*UnregisterServerRequest)(nil),     // 6: yggplane.v1.UnregisterServerRequest
	(*AssignPlayerRequest)(nil),         // 7: yggplane.v1.AssignPlayerRequest
	(*UpdatePlayerPositionRequest)(nil), // 8: yggplane.v1.UpdatePlayerPositionRequest
	(*CompleteMigrationRequest)(nil),    // 9: yggplane.v1.CompleteMigrationRequest
	(*ServerId)(nil),                    // 10: yggplane.v1.ServerId
	(*PlayerId)(nil),                    // 11: yggplane.v1.PlayerId
	(*Server)(nil),                      // 12: yggplane.v1.Server
	(*Position)(nil),                    // 13: yggplane.v1.Position
}
var file_controlplane_proto_depIdxs = []int32{
	10, // 0: yggplane.v1.OpenControlStreamRequest.server_id:type_name -> yggplane.v1.ServerId
	0,  // 1: yggplane.v1.ControlEvent.type:type_name -> yggplane.v1.ControlEventType
	3,  // 2: yggplane.v1.ControlEvent.migrate_out:type_name -> yggplane.v1.MigrateOutEvent
	11, // 3: yggplane.v1.MigrateOutEvent.player_id:type_name -> yggplane.v1.PlayerId
	12, // 4: yggplane.v1.MigrateOutEvent.new_server:type_name -> yggplane.v1.Server
	12, // 5: yggplane.v1.RegisterServerRequest.server:type_name -> yggplane.v1.Server
	10, // 6: yggplane.v1.UnregisterServerRequest.server_id:type_name -> yggplane.v1.ServerId
	11, // 7: yggplane.v1.AssignPlayerRequest.player_id:type_name -> yggplane.v1.PlayerId
	13, // 8: yggplane.v1.AssignPlayerRequest.position:type_name -> yggplane.v1.Position
	11, // 9: yggplane.v1.UpdatePlayerPositionRequest.player_id:type_name -> yggplane.v1.PlayerId
	13, // 10: yggplane.v1.UpdatePlayerPositionRequest.position:type_name -> yggplane.v1.Position
	11, // 11: yggplane.v1.CompleteMigrationRequest.player_id:type_name -> yggplane.v1.PlayerId
	10, // 12: yggplane.v1.CompleteMigrationRequest.server_id:type_name -> yggplane.v1.ServerId
	1,  // 13: yggplane.v1.ControlService.OpenControlStream:input_type -> yggplane.v1.OpenControlStreamRequest
	5,  // 14: yggplane.v1.ControlService.RegisterServer:input_type -> yggplane.v1.RegisterServerRequest
	6,  // 15: yggplane.v1.ControlService.UnregisterServer:input_type -> yggplane.v1.UnregisterServerRequest
	7,  // 16: yggplane.v1.ControlService.AssignPlayer:input_type -> yggplane.v1.AssignPlayerRequest
	8,  // 17: yggplane.v1.ControlService.UpdatePlayerPosition:input_type -> yggplane.v1.UpdatePlayerPositionRequest
	9,  // 18: yggplane.v1.ControlService.CompleteMigration:input_type -> yggplane.v1.CompleteMigrationRequest
	2,  // 19: yggplane.v1.ControlService.OpenControlStream:output_type -> yggplane.v1.ControlEvent
	4,  // 20: yggplane.v1.ControlService.RegisterServer:output_type -> yggplane.v1.ControlAck
	4,  // 21: yggplane.v1.ControlService.UnregisterServer:output_type -> yggplane.v1.ControlAck
	4,  // 22: yggplane.v1.ControlService.AssignPlayer:output_type -> yggplane.v1.ControlAck
	4,  // 23: yggplane.v1.ControlService.UpdatePlayerPosition:output_type -> yggplane.v1.ControlAck
	4,  // 24: yggplane.v1.ControlService.CompleteMigration:output_type -> yggplane.v1.ControlAck
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_controlplane_proto_init() }
func file_controlplane_proto_init() {
	if File_controlplane_proto != nil {
		return
	}
	file_common_proto_init()
	file_controlplane_proto_msgTypes[1].OneofWrappers = []any{
		(*ControlEvent_MigrateOut)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_proto_rawDesc), len(file_controlplane_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controlplane_proto_goTypes,
		DependencyIndexes: file_controlplane_proto_depIdxs,
		EnumInfos:         file_controlplane_proto_enumTypes,
		MessageInfos:      file_controlplane_proto_msgTypes,
	}.Build()
	File_controlplane_proto = out.File
	file_controlplane_proto_goTypes = nil
	file_controlplane_proto_depIdxs = nil
}
