// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: controlplane.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Types of control-plane events
type ControlEventType int32

const (
	ControlEventType_CONTROL_EVENT_UNSPECIFIED ControlEventType = 0
)

// Enum value maps for ControlEventType.
var (
	ControlEventType_name = map[int32]string{
		0: "CONTROL_EVENT_UNSPECIFIED",
	}
	ControlEventType_value = map[string]int32{
		"CONTROL_EVENT_UNSPECIFIED": 0,
	}
)

func (x ControlEventType) Enum() *ControlEventType {
	p := new(ControlEventType)
	*p = x
	return p
}

func (x ControlEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_controlplane_proto_enumTypes[0].Descriptor()
}

func (ControlEventType) Type() protoreflect.EnumType {
	return &file_controlplane_proto_enumTypes[0]
}

func (x ControlEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlEventType.Descriptor instead.
func (ControlEventType) EnumDescriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{0}
}

type OpenControlStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      *ServerId              `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenControlStreamRequest) Reset() {
	*x = OpenControlStreamRequest{}
	mi := &file_controlplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenControlStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenControlStreamRequest) ProtoMessage() {}

func (x *OpenControlStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenControlStreamRequest.ProtoReflect.Descriptor instead.
func (*OpenControlStreamRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{0}
}

func (x *OpenControlStreamRequest) GetServerId() *ServerId {
	if x != nil {
		return x.ServerId
	}
	return nil
}

type ControlEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ControlEventType       `protobuf:"varint,1,opt,name=type,proto3,enum=yggplane.v1.ControlEventType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlEvent) Reset() {
	*x = ControlEvent{}
	mi := &file_controlplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlEvent) ProtoMessage() {}

func (x *ControlEvent) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlEvent.ProtoReflect.Descriptor instead.
func (*ControlEvent) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{1}
}

func (x *ControlEvent) GetType() ControlEventType {
	if x != nil {
		return x.Type
	}
	return ControlEventType_CONTROL_EVENT_UNSPECIFIED
}

var File_controlplane_proto protoreflect.FileDescriptor

const file_controlplane_proto_rawDesc = "" +
	"\n" +
	"\x12controlplane.proto\x12\vyggplane.v1\x1a\fcommon.proto\"N\n" +
	"\x18OpenControlStreamRequest\x122\n" +
	"\tserver_id\x18\x01 \x01(\v2\x15.yggplane.v1.ServerIdR\bserverId\"A\n" +
	"\fControlEvent\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.yggplane.v1.ControlEventTypeR\x04type*1\n" +
	"\x10ControlEventType\x12\x1d\n" +
	"\x19CONTROL_EVENT_UNSPECIFIED\x10\x002i\n" +
	"\x0eControlService\x12W\n" +
	"\x11OpenControlStream\x12%.yggplane.v1.OpenControlStreamRequest\x1a\x19.yggplane.v1.ControlEvent0\x01B-Z+github.com/didopimentel/yggdrasil/api/pb;pbb\x06proto3"

var (
	file_controlplane_proto_rawDescOnce sync.Once
	file_controlplane_proto_rawDescData []byte
)

func file_controlplane_proto_rawDescGZIP() []byte {
	file_controlplane_proto_rawDescOnce.Do(func() {
		file_controlplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_proto_rawDesc), len(file_controlplane_proto_rawDesc)))
	})
	return file_controlplane_proto_rawDescData
}

var file_controlplane_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_controlplane_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_controlplane_proto_goTypes = []any{
	(ControlEventType)(0),            // 0: yggplane.v1.ControlEventType
	(*OpenControlStreamRequest)(nil), // 1: yggplane.v1.OpenControlStreamRequest
	(*ControlEvent)(nil),             // 2: yggplane.v1.ControlEvent
	(*ServerId)(nil),                 // 3: yggplane.v1.ServerId
}
var file_controlplane_proto_depIdxs = []int32{
	3, // 0: yggplane.v1.OpenControlStreamRequest.server_id:type_name -> yggplane.v1.ServerId
	0, // 1: yggplane.v1.ControlEvent.type:type_name -> yggplane.v1.ControlEventType
	1, // 2: yggplane.v1.ControlService.OpenControlStream:input_type -> yggplane.v1.OpenControlStreamRequest
	2, // 3: yggplane.v1.ControlService.OpenControlStream:output_type -> yggplane.v1.ControlEvent
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_controlplane_proto_init() }
func file_controlplane_proto_init() {
	if File_controlplane_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_proto_rawDesc), len(file_controlplane_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controlplane_proto_goTypes,
		DependencyIndexes: file_controlplane_proto_depIdxs,
		EnumInfos:         file_controlplane_proto_enumTypes,
		MessageInfos:      file_controlplane_proto_msgTypes,
	}.Build()
	File_controlplane_proto = out.File
	file_controlplane_proto_goTypes = nil
	file_controlplane_proto_depIdxs = nil
}
