// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: controlplane.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlService_OpenControlStream_FullMethodName    = "/yggplane.v1.ControlService/OpenControlStream"
	ControlService_RegisterServer_FullMethodName       = "/yggplane.v1.ControlService/RegisterServer"
	ControlService_UnregisterServer_FullMethodName     = "/yggplane.v1.ControlService/UnregisterServer"
	ControlService_AssignPlayer_FullMethodName         = "/yggplane.v1.ControlService/AssignPlayer"
	ControlService_UpdatePlayerPosition_FullMethodName = "/yggplane.v1.ControlService/UpdatePlayerPosition"
	ControlService_CompleteMigration_FullMethodName    = "/yggplane.v1.ControlService/CompleteMigration"
)

// ControlServiceClient is the client API for ControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlServiceClient interface {
	// GS opens outbound stream; CP pushes events down it
	OpenControlStream(ctx context.Context, in *OpenControlStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ControlEvent], error)
	// Inbound ops use streaming for throughput; server replies with per-message acks
	RegisterServer(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RegisterServerRequest, ControlAck], error)
	UnregisterServer(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UnregisterServerRequest, ControlAck], error)
	AssignPlayer(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AssignPlayerRequest, ControlAck], error)
	UpdatePlayerPosition(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UpdatePlayerPositionRequest, ControlAck], error)
	CompleteMigration(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CompleteMigrationRequest, ControlAck], error)
}

type controlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlServiceClient(cc grpc.ClientConnInterface) ControlServiceClient {
	return &controlServiceClient{cc}
}

func (c *controlServiceClient) OpenControlStream(ctx context.Context, in *OpenControlStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ControlEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlService_ServiceDesc.Streams[0], ControlService_OpenControlStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OpenControlStreamRequest, ControlEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_OpenControlStreamClient = grpc.ServerStreamingClient[ControlEvent]

func (c *controlServiceClient) RegisterServer(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RegisterServerRequest, ControlAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlService_ServiceDesc.Streams[1], ControlService_RegisterServer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RegisterServerRequest, ControlAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_RegisterServerClient = grpc.BidiStreamingClient[RegisterServerRequest, ControlAck]

func (c *controlServiceClient) UnregisterServer(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UnregisterServerRequest, ControlAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlService_ServiceDesc.Streams[2], ControlService_UnregisterServer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UnregisterServerRequest, ControlAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_UnregisterServerClient = grpc.BidiStreamingClient[UnregisterServerRequest, ControlAck]

func (c *controlServiceClient) AssignPlayer(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AssignPlayerRequest, ControlAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlService_ServiceDesc.Streams[3], ControlService_AssignPlayer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AssignPlayerRequest, ControlAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_AssignPlayerClient = grpc.BidiStreamingClient[AssignPlayerRequest, ControlAck]

func (c *controlServiceClient) UpdatePlayerPosition(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UpdatePlayerPositionRequest, ControlAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlService_ServiceDesc.Streams[4], ControlService_UpdatePlayerPosition_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UpdatePlayerPositionRequest, ControlAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_UpdatePlayerPositionClient = grpc.BidiStreamingClient[UpdatePlayerPositionRequest, ControlAck]

func (c *controlServiceClient) CompleteMigration(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CompleteMigrationRequest, ControlAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlService_ServiceDesc.Streams[5], ControlService_CompleteMigration_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CompleteMigrationRequest, ControlAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_CompleteMigrationClient = grpc.BidiStreamingClient[CompleteMigrationRequest, ControlAck]

// ControlServiceServer is the server API for ControlService service.
// All implementations must embed UnimplementedControlServiceServer
// for forward compatibility.
type ControlServiceServer interface {
	// GS opens outbound stream; CP pushes events down it
	OpenControlStream(*OpenControlStreamRequest, grpc.ServerStreamingServer[ControlEvent]) error
	// Inbound ops use streaming for throughput; server replies with per-message acks
	RegisterServer(grpc.BidiStreamingServer[RegisterServerRequest, ControlAck]) error
	UnregisterServer(grpc.BidiStreamingServer[UnregisterServerRequest, ControlAck]) error
	AssignPlayer(grpc.BidiStreamingServer[AssignPlayerRequest, ControlAck]) error
	UpdatePlayerPosition(grpc.BidiStreamingServer[UpdatePlayerPositionRequest, ControlAck]) error
	CompleteMigration(grpc.BidiStreamingServer[CompleteMigrationRequest, ControlAck]) error
	mustEmbedUnimplementedControlServiceServer()
}

// UnimplementedControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlServiceServer struct{}

func (UnimplementedControlServiceServer) OpenControlStream(*OpenControlStreamRequest, grpc.ServerStreamingServer[ControlEvent]) error {
	return status.Error(codes.Unimplemented, "method OpenControlStream not implemented")
}
func (UnimplementedControlServiceServer) RegisterServer(grpc.BidiStreamingServer[RegisterServerRequest, ControlAck]) error {
	return status.Error(codes.Unimplemented, "method RegisterServer not implemented")
}
func (UnimplementedControlServiceServer) UnregisterServer(grpc.BidiStreamingServer[UnregisterServerRequest, ControlAck]) error {
	return status.Error(codes.Unimplemented, "method UnregisterServer not implemented")
}
func (UnimplementedControlServiceServer) AssignPlayer(grpc.BidiStreamingServer[AssignPlayerRequest, ControlAck]) error {
	return status.Error(codes.Unimplemented, "method AssignPlayer not implemented")
}
func (UnimplementedControlServiceServer) UpdatePlayerPosition(grpc.BidiStreamingServer[UpdatePlayerPositionRequest, ControlAck]) error {
	return status.Error(codes.Unimplemented, "method UpdatePlayerPosition not implemented")
}
func (UnimplementedControlServiceServer) CompleteMigration(grpc.BidiStreamingServer[CompleteMigrationRequest, ControlAck]) error {
	return status.Error(codes.Unimplemented, "method CompleteMigration not implemented")
}
func (UnimplementedControlServiceServer) mustEmbedUnimplementedControlServiceServer() {}
func (UnimplementedControlServiceServer) testEmbeddedByValue()                        {}

// UnsafeControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlServiceServer will
// result in compilation errors.
type UnsafeControlServiceServer interface {
	mustEmbedUnimplementedControlServiceServer()
}

func RegisterControlServiceServer(s grpc.ServiceRegistrar, srv ControlServiceServer) {
	// If the following call panics, it indicates UnimplementedControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlService_ServiceDesc, srv)
}

func _ControlService_OpenControlStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OpenControlStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlServiceServer).OpenControlStream(m, &grpc.GenericServerStream[OpenControlStreamRequest, ControlEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_OpenControlStreamServer = grpc.ServerStreamingServer[ControlEvent]

func _ControlService_RegisterServer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlServiceServer).RegisterServer(&grpc.GenericServerStream[RegisterServerRequest, ControlAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_RegisterServerServer = grpc.BidiStreamingServer[RegisterServerRequest, ControlAck]

func _ControlService_UnregisterServer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlServiceServer).UnregisterServer(&grpc.GenericServerStream[UnregisterServerRequest, ControlAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_UnregisterServerServer = grpc.BidiStreamingServer[UnregisterServerRequest, ControlAck]

func _ControlService_AssignPlayer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlServiceServer).AssignPlayer(&grpc.GenericServerStream[AssignPlayerRequest, ControlAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_AssignPlayerServer = grpc.BidiStreamingServer[AssignPlayerRequest, ControlAck]

func _ControlService_UpdatePlayerPosition_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlServiceServer).UpdatePlayerPosition(&grpc.GenericServerStream[UpdatePlayerPositionRequest, ControlAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_UpdatePlayerPositionServer = grpc.BidiStreamingServer[UpdatePlayerPositionRequest, ControlAck]

func _ControlService_CompleteMigration_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlServiceServer).CompleteMigration(&grpc.GenericServerStream[CompleteMigrationRequest, ControlAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_CompleteMigrationServer = grpc.BidiStreamingServer[CompleteMigrationRequest, ControlAck]

// ControlService_ServiceDesc is the grpc.ServiceDesc for ControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yggplane.v1.ControlService",
	HandlerType: (*ControlServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenControlStream",
			Handler:       _ControlService_OpenControlStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RegisterServer",
			Handler:       _ControlService_RegisterServer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "UnregisterServer",
			Handler:       _ControlService_UnregisterServer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "AssignPlayer",
			Handler:       _ControlService_AssignPlayer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "UpdatePlayerPosition",
			Handler:       _ControlService_UpdatePlayerPosition_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CompleteMigration",
			Handler:       _ControlService_CompleteMigration_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "controlplane.proto",
}
