// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: control.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Types of control-plane events
type ControlEventType int32

const (
	ControlEventType_CONTROL_EVENT_UNSPECIFIED ControlEventType = 0
	ControlEventType_CONTROL_EVENT_MIGRATE_OUT ControlEventType = 1
)

// Enum value maps for ControlEventType.
var (
	ControlEventType_name = map[int32]string{
		0: "CONTROL_EVENT_UNSPECIFIED",
		1: "CONTROL_EVENT_MIGRATE_OUT",
	}
	ControlEventType_value = map[string]int32{
		"CONTROL_EVENT_UNSPECIFIED": 0,
		"CONTROL_EVENT_MIGRATE_OUT": 1,
	}
)

func (x ControlEventType) Enum() *ControlEventType {
	p := new(ControlEventType)
	*p = x
	return p
}

func (x ControlEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_control_proto_enumTypes[0].Descriptor()
}

func (ControlEventType) Type() protoreflect.EnumType {
	return &file_control_proto_enumTypes[0]
}

func (x ControlEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlEventType.Descriptor instead.
func (ControlEventType) EnumDescriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

type OpenControlStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      *ServerId              `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenControlStreamRequest) Reset() {
	*x = OpenControlStreamRequest{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenControlStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenControlStreamRequest) ProtoMessage() {}

func (x *OpenControlStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenControlStreamRequest.ProtoReflect.Descriptor instead.
func (*OpenControlStreamRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *OpenControlStreamRequest) GetServerId() *ServerId {
	if x != nil {
		return x.ServerId
	}
	return nil
}

type ControlEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  ControlEventType       `protobuf:"varint,1,opt,name=type,proto3,enum=yggplane.v1.ControlEventType" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlEvent_MigrateOut
	Payload       isControlEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlEvent) Reset() {
	*x = ControlEvent{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlEvent) ProtoMessage() {}

func (x *ControlEvent) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlEvent.ProtoReflect.Descriptor instead.
func (*ControlEvent) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *ControlEvent) GetType() ControlEventType {
	if x != nil {
		return x.Type
	}
	return ControlEventType_CONTROL_EVENT_UNSPECIFIED
}

func (x *ControlEvent) GetPayload() isControlEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlEvent) GetMigrateOut() *MigrateOutEvent {
	if x != nil {
		if x, ok := x.Payload.(*ControlEvent_MigrateOut); ok {
			return x.MigrateOut
		}
	}
	return nil
}

type isControlEvent_Payload interface {
	isControlEvent_Payload()
}

type ControlEvent_MigrateOut struct {
	MigrateOut *MigrateOutEvent `protobuf:"bytes,2,opt,name=migrate_out,json=migrateOut,proto3,oneof"`
}

func (*ControlEvent_MigrateOut) isControlEvent_Payload() {}

type MigrateOutEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      *PlayerId              `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	NewServer     *Server                `protobuf:"bytes,2,opt,name=new_server,json=newServer,proto3" json:"new_server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateOutEvent) Reset() {
	*x = MigrateOutEvent{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateOutEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateOutEvent) ProtoMessage() {}

func (x *MigrateOutEvent) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateOutEvent.ProtoReflect.Descriptor instead.
func (*MigrateOutEvent) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *MigrateOutEvent) GetPlayerId() *PlayerId {
	if x != nil {
		return x.PlayerId
	}
	return nil
}

func (x *MigrateOutEvent) GetNewServer() *Server {
	if x != nil {
		return x.NewServer
	}
	return nil
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\vyggplane.v1\x1a\fcommon.proto\"N\n" +
	"\x18OpenControlStreamRequest\x122\n" +
	"\tserver_id\x18\x01 \x01(\v2\x15.yggplane.v1.ServerIdR\bserverId\"\x8d\x01\n" +
	"\fControlEvent\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.yggplane.v1.ControlEventTypeR\x04type\x12?\n" +
	"\vmigrate_out\x18\x02 \x01(\v2\x1c.yggplane.v1.MigrateOutEventH\x00R\n" +
	"migrateOutB\t\n" +
	"\apayload\"y\n" +
	"\x0fMigrateOutEvent\x122\n" +
	"\tplayer_id\x18\x01 \x01(\v2\x15.yggplane.v1.PlayerIdR\bplayerId\x122\n" +
	"\n" +
	"new_server\x18\x02 \x01(\v2\x13.yggplane.v1.ServerR\tnewServer*P\n" +
	"\x10ControlEventType\x12\x1d\n" +
	"\x19CONTROL_EVENT_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19CONTROL_EVENT_MIGRATE_OUT\x10\x012i\n" +
	"\x0eControlService\x12W\n" +
	"\x11OpenControlStream\x12%.yggplane.v1.OpenControlStreamRequest\x1a\x19.yggplane.v1.ControlEvent0\x01B-Z+github.com/didopimentel/yggdrasil/api/pb;pbb\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_control_proto_goTypes = []any{
	(ControlEventType)(0),            // 0: yggplane.v1.ControlEventType
	(*OpenControlStreamRequest)(nil), // 1: yggplane.v1.OpenControlStreamRequest
	(*ControlEvent)(nil),             // 2: yggplane.v1.ControlEvent
	(*MigrateOutEvent)(nil),          // 3: yggplane.v1.MigrateOutEvent
	(*ServerId)(nil),                 // 4: yggplane.v1.ServerId
	(*PlayerId)(nil),                 // 5: yggplane.v1.PlayerId
	(*Server)(nil),                   // 6: yggplane.v1.Server
}
var file_control_proto_depIdxs = []int32{
	4, // 0: yggplane.v1.OpenControlStreamRequest.server_id:type_name -> yggplane.v1.ServerId
	0, // 1: yggplane.v1.ControlEvent.type:type_name -> yggplane.v1.ControlEventType
	3, // 2: yggplane.v1.ControlEvent.migrate_out:type_name -> yggplane.v1.MigrateOutEvent
	5, // 3: yggplane.v1.MigrateOutEvent.player_id:type_name -> yggplane.v1.PlayerId
	6, // 4: yggplane.v1.MigrateOutEvent.new_server:type_name -> yggplane.v1.Server
	1, // 5: yggplane.v1.ControlService.OpenControlStream:input_type -> yggplane.v1.OpenControlStreamRequest
	2, // 6: yggplane.v1.ControlService.OpenControlStream:output_type -> yggplane.v1.ControlEvent
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	file_common_proto_init()
	file_control_proto_msgTypes[1].OneofWrappers = []any{
		(*ControlEvent_MigrateOut)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		EnumInfos:         file_control_proto_enumTypes,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
