// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: placement.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssignPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      *PlayerId              `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Position      *Position              `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignPlayerRequest) Reset() {
	*x = AssignPlayerRequest{}
	mi := &file_placement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPlayerRequest) ProtoMessage() {}

func (x *AssignPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_placement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPlayerRequest.ProtoReflect.Descriptor instead.
func (*AssignPlayerRequest) Descriptor() ([]byte, []int) {
	return file_placement_proto_rawDescGZIP(), []int{0}
}

func (x *AssignPlayerRequest) GetPlayerId() *PlayerId {
	if x != nil {
		return x.PlayerId
	}
	return nil
}

func (x *AssignPlayerRequest) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type UpdatePlayerPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      *PlayerId              `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Position      *Position              `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlayerPositionRequest) Reset() {
	*x = UpdatePlayerPositionRequest{}
	mi := &file_placement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlayerPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerPositionRequest) ProtoMessage() {}

func (x *UpdatePlayerPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_placement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerPositionRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlayerPositionRequest) Descriptor() ([]byte, []int) {
	return file_placement_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatePlayerPositionRequest) GetPlayerId() *PlayerId {
	if x != nil {
		return x.PlayerId
	}
	return nil
}

func (x *UpdatePlayerPositionRequest) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type CompleteMigrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      *PlayerId              `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ServerId      *ServerId              `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteMigrationRequest) Reset() {
	*x = CompleteMigrationRequest{}
	mi := &file_placement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMigrationRequest) ProtoMessage() {}

func (x *CompleteMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_placement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMigrationRequest.ProtoReflect.Descriptor instead.
func (*CompleteMigrationRequest) Descriptor() ([]byte, []int) {
	return file_placement_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteMigrationRequest) GetPlayerId() *PlayerId {
	if x != nil {
		return x.PlayerId
	}
	return nil
}

func (x *CompleteMigrationRequest) GetServerId() *ServerId {
	if x != nil {
		return x.ServerId
	}
	return nil
}

var File_placement_proto protoreflect.FileDescriptor

const file_placement_proto_rawDesc = "" +
	"\n" +
	"\x0fplacement.proto\x12\vyggplane.v1\x1a\fcommon.proto\"|\n" +
	"\x13AssignPlayerRequest\x122\n" +
	"\tplayer_id\x18\x01 \x01(\v2\x15.yggplane.v1.PlayerIdR\bplayerId\x121\n" +
	"\bposition\x18\x02 \x01(\v2\x15.yggplane.v1.PositionR\bposition\"\x84\x01\n" +
	"\x1bUpdatePlayerPositionRequest\x122\n" +
	"\tplayer_id\x18\x01 \x01(\v2\x15.yggplane.v1.PlayerIdR\bplayerId\x121\n" +
	"\bposition\x18\x02 \x01(\v2\x15.yggplane.v1.PositionR\bposition\"\x82\x01\n" +
	"\x18CompleteMigrationRequest\x122\n" +
	"\tplayer_id\x18\x01 \x01(\v2\x15.yggplane.v1.PlayerIdR\bplayerId\x122\n" +
	"\tserver_id\x18\x02 \x01(\v2\x15.yggplane.v1.ServerIdR\bserverId2\x99\x02\n" +
	"\x10PlacementService\x12M\n" +
	"\fAssignPlayer\x12 .yggplane.v1.AssignPlayerRequest\x1a\x17.yggplane.v1.ControlAck(\x010\x01\x12]\n" +
	"\x14UpdatePlayerPosition\x12(.yggplane.v1.UpdatePlayerPositionRequest\x1a\x17.yggplane.v1.ControlAck(\x010\x01\x12W\n" +
	"\x11CompleteMigration\x12%.yggplane.v1.CompleteMigrationRequest\x1a\x17.yggplane.v1.ControlAck(\x010\x01B-Z+github.com/didopimentel/yggdrasil/api/pb;pbb\x06proto3"

var (
	file_placement_proto_rawDescOnce sync.Once
	file_placement_proto_rawDescData []byte
)

func file_placement_proto_rawDescGZIP() []byte {
	file_placement_proto_rawDescOnce.Do(func() {
		file_placement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_placement_proto_rawDesc), len(file_placement_proto_rawDesc)))
	})
	return file_placement_proto_rawDescData
}

var file_placement_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_placement_proto_goTypes = []any{
	(*AssignPlayerRequest)(nil),         // 0: yggplane.v1.AssignPlayerRequest
	(*UpdatePlayerPositionRequest)(nil), // 1: yggplane.v1.UpdatePlayerPositionRequest
	(*CompleteMigrationRequest)(nil),    // 2: yggplane.v1.CompleteMigrationRequest
	(*PlayerId)(nil),                    // 3: yggplane.v1.PlayerId
	(*Position)(nil),                    // 4: yggplane.v1.Position
	(*ServerId)(nil),                    // 5: yggplane.v1.ServerId
	(*ControlAck)(nil),                  // 6: yggplane.v1.ControlAck
}
var file_placement_proto_depIdxs = []int32{
	3, // 0: yggplane.v1.AssignPlayerRequest.player_id:type_name -> yggplane.v1.PlayerId
	4, // 1: yggplane.v1.AssignPlayerRequest.position:type_name -> yggplane.v1.Position
	3, // 2: yggplane.v1.UpdatePlayerPositionRequest.player_id:type_name -> yggplane.v1.PlayerId
	4, // 3: yggplane.v1.UpdatePlayerPositionRequest.position:type_name -> yggplane.v1.Position
	3, // 4: yggplane.v1.CompleteMigrationRequest.player_id:type_name -> yggplane.v1.PlayerId
	5, // 5: yggplane.v1.CompleteMigrationRequest.server_id:type_name -> yggplane.v1.ServerId
	0, // 6: yggplane.v1.PlacementService.AssignPlayer:input_type -> yggplane.v1.AssignPlayerRequest
	1, // 7: yggplane.v1.PlacementService.UpdatePlayerPosition:input_type -> yggplane.v1.UpdatePlayerPositionRequest
	2, // 8: yggplane.v1.PlacementService.CompleteMigration:input_type -> yggplane.v1.CompleteMigrationRequest
	6, // 9: yggplane.v1.PlacementService.AssignPlayer:output_type -> yggplane.v1.ControlAck
	6, // 10: yggplane.v1.PlacementService.UpdatePlayerPosition:output_type -> yggplane.v1.ControlAck
	6, // 11: yggplane.v1.PlacementService.CompleteMigration:output_type -> yggplane.v1.ControlAck
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_placement_proto_init() }
func file_placement_proto_init() {
	if File_placement_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_placement_proto_rawDesc), len(file_placement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_placement_proto_goTypes,
		DependencyIndexes: file_placement_proto_depIdxs,
		MessageInfos:      file_placement_proto_msgTypes,
	}.Build()
	File_placement_proto = out.File
	file_placement_proto_goTypes = nil
	file_placement_proto_depIdxs = nil
}
