// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: placement.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlacementService_AssignPlayer_FullMethodName         = "/yggplane.v1.PlacementService/AssignPlayer"
	PlacementService_UpdatePlayerPosition_FullMethodName = "/yggplane.v1.PlacementService/UpdatePlayerPosition"
	PlacementService_CompleteMigration_FullMethodName    = "/yggplane.v1.PlacementService/CompleteMigration"
)

// PlacementServiceClient is the client API for PlacementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Player placement and migration operations
type PlacementServiceClient interface {
	AssignPlayer(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AssignPlayerRequest, ControlAck], error)
	UpdatePlayerPosition(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UpdatePlayerPositionRequest, ControlAck], error)
	CompleteMigration(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CompleteMigrationRequest, ControlAck], error)
}

type placementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlacementServiceClient(cc grpc.ClientConnInterface) PlacementServiceClient {
	return &placementServiceClient{cc}
}

func (c *placementServiceClient) AssignPlayer(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AssignPlayerRequest, ControlAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PlacementService_ServiceDesc.Streams[0], PlacementService_AssignPlayer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AssignPlayerRequest, ControlAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlacementService_AssignPlayerClient = grpc.BidiStreamingClient[AssignPlayerRequest, ControlAck]

func (c *placementServiceClient) UpdatePlayerPosition(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UpdatePlayerPositionRequest, ControlAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PlacementService_ServiceDesc.Streams[1], PlacementService_UpdatePlayerPosition_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UpdatePlayerPositionRequest, ControlAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlacementService_UpdatePlayerPositionClient = grpc.BidiStreamingClient[UpdatePlayerPositionRequest, ControlAck]

func (c *placementServiceClient) CompleteMigration(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CompleteMigrationRequest, ControlAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PlacementService_ServiceDesc.Streams[2], PlacementService_CompleteMigration_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CompleteMigrationRequest, ControlAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlacementService_CompleteMigrationClient = grpc.BidiStreamingClient[CompleteMigrationRequest, ControlAck]

// PlacementServiceServer is the server API for PlacementService service.
// All implementations must embed UnimplementedPlacementServiceServer
// for forward compatibility.
//
// Player placement and migration operations
type PlacementServiceServer interface {
	AssignPlayer(grpc.BidiStreamingServer[AssignPlayerRequest, ControlAck]) error
	UpdatePlayerPosition(grpc.BidiStreamingServer[UpdatePlayerPositionRequest, ControlAck]) error
	CompleteMigration(grpc.BidiStreamingServer[CompleteMigrationRequest, ControlAck]) error
	mustEmbedUnimplementedPlacementServiceServer()
}

// UnimplementedPlacementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlacementServiceServer struct{}

func (UnimplementedPlacementServiceServer) AssignPlayer(grpc.BidiStreamingServer[AssignPlayerRequest, ControlAck]) error {
	return status.Error(codes.Unimplemented, "method AssignPlayer not implemented")
}
func (UnimplementedPlacementServiceServer) UpdatePlayerPosition(grpc.BidiStreamingServer[UpdatePlayerPositionRequest, ControlAck]) error {
	return status.Error(codes.Unimplemented, "method UpdatePlayerPosition not implemented")
}
func (UnimplementedPlacementServiceServer) CompleteMigration(grpc.BidiStreamingServer[CompleteMigrationRequest, ControlAck]) error {
	return status.Error(codes.Unimplemented, "method CompleteMigration not implemented")
}
func (UnimplementedPlacementServiceServer) mustEmbedUnimplementedPlacementServiceServer() {}
func (UnimplementedPlacementServiceServer) testEmbeddedByValue()                          {}

// UnsafePlacementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlacementServiceServer will
// result in compilation errors.
type UnsafePlacementServiceServer interface {
	mustEmbedUnimplementedPlacementServiceServer()
}

func RegisterPlacementServiceServer(s grpc.ServiceRegistrar, srv PlacementServiceServer) {
	// If the following call panics, it indicates UnimplementedPlacementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlacementService_ServiceDesc, srv)
}

func _PlacementService_AssignPlayer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PlacementServiceServer).AssignPlayer(&grpc.GenericServerStream[AssignPlayerRequest, ControlAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlacementService_AssignPlayerServer = grpc.BidiStreamingServer[AssignPlayerRequest, ControlAck]

func _PlacementService_UpdatePlayerPosition_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PlacementServiceServer).UpdatePlayerPosition(&grpc.GenericServerStream[UpdatePlayerPositionRequest, ControlAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlacementService_UpdatePlayerPositionServer = grpc.BidiStreamingServer[UpdatePlayerPositionRequest, ControlAck]

func _PlacementService_CompleteMigration_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PlacementServiceServer).CompleteMigration(&grpc.GenericServerStream[CompleteMigrationRequest, ControlAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlacementService_CompleteMigrationServer = grpc.BidiStreamingServer[CompleteMigrationRequest, ControlAck]

// PlacementService_ServiceDesc is the grpc.ServiceDesc for PlacementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlacementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yggplane.v1.PlacementService",
	HandlerType: (*PlacementServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AssignPlayer",
			Handler:       _PlacementService_AssignPlayer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "UpdatePlayerPosition",
			Handler:       _PlacementService_UpdatePlayerPosition_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CompleteMigration",
			Handler:       _PlacementService_CompleteMigration_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "placement.proto",
}
