// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: servermanager.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServerManagerService_RegisterServer_FullMethodName   = "/yggplane.v1.ServerManagerService/RegisterServer"
	ServerManagerService_UnregisterServer_FullMethodName = "/yggplane.v1.ServerManagerService/UnregisterServer"
)

// ServerManagerServiceClient is the client API for ServerManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Server lifecycle operations
type ServerManagerServiceClient interface {
	RegisterServer(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RegisterServerRequest, ControlAck], error)
	UnregisterServer(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UnregisterServerRequest, ControlAck], error)
}

type serverManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewServerManagerServiceClient(cc grpc.ClientConnInterface) ServerManagerServiceClient {
	return &serverManagerServiceClient{cc}
}

func (c *serverManagerServiceClient) RegisterServer(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RegisterServerRequest, ControlAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ServerManagerService_ServiceDesc.Streams[0], ServerManagerService_RegisterServer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RegisterServerRequest, ControlAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ServerManagerService_RegisterServerClient = grpc.BidiStreamingClient[RegisterServerRequest, ControlAck]

func (c *serverManagerServiceClient) UnregisterServer(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UnregisterServerRequest, ControlAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ServerManagerService_ServiceDesc.Streams[1], ServerManagerService_UnregisterServer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UnregisterServerRequest, ControlAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ServerManagerService_UnregisterServerClient = grpc.BidiStreamingClient[UnregisterServerRequest, ControlAck]

// ServerManagerServiceServer is the server API for ServerManagerService service.
// All implementations must embed UnimplementedServerManagerServiceServer
// for forward compatibility.
//
// Server lifecycle operations
type ServerManagerServiceServer interface {
	RegisterServer(grpc.BidiStreamingServer[RegisterServerRequest, ControlAck]) error
	UnregisterServer(grpc.BidiStreamingServer[UnregisterServerRequest, ControlAck]) error
	mustEmbedUnimplementedServerManagerServiceServer()
}

// UnimplementedServerManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServerManagerServiceServer struct{}

func (UnimplementedServerManagerServiceServer) RegisterServer(grpc.BidiStreamingServer[RegisterServerRequest, ControlAck]) error {
	return status.Error(codes.Unimplemented, "method RegisterServer not implemented")
}
func (UnimplementedServerManagerServiceServer) UnregisterServer(grpc.BidiStreamingServer[UnregisterServerRequest, ControlAck]) error {
	return status.Error(codes.Unimplemented, "method UnregisterServer not implemented")
}
func (UnimplementedServerManagerServiceServer) mustEmbedUnimplementedServerManagerServiceServer() {}
func (UnimplementedServerManagerServiceServer) testEmbeddedByValue()                              {}

// UnsafeServerManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServerManagerServiceServer will
// result in compilation errors.
type UnsafeServerManagerServiceServer interface {
	mustEmbedUnimplementedServerManagerServiceServer()
}

func RegisterServerManagerServiceServer(s grpc.ServiceRegistrar, srv ServerManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedServerManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServerManagerService_ServiceDesc, srv)
}

func _ServerManagerService_RegisterServer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServerManagerServiceServer).RegisterServer(&grpc.GenericServerStream[RegisterServerRequest, ControlAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ServerManagerService_RegisterServerServer = grpc.BidiStreamingServer[RegisterServerRequest, ControlAck]

func _ServerManagerService_UnregisterServer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServerManagerServiceServer).UnregisterServer(&grpc.GenericServerStream[UnregisterServerRequest, ControlAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ServerManagerService_UnregisterServerServer = grpc.BidiStreamingServer[UnregisterServerRequest, ControlAck]

// ServerManagerService_ServiceDesc is the grpc.ServiceDesc for ServerManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServerManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yggplane.v1.ServerManagerService",
	HandlerType: (*ServerManagerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterServer",
			Handler:       _ServerManagerService_RegisterServer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "UnregisterServer",
			Handler:       _ServerManagerService_UnregisterServer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "servermanager.proto",
}
