// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: servermanager.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServerRequest) Reset() {
	*x = RegisterServerRequest{}
	mi := &file_servermanager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServerRequest) ProtoMessage() {}

func (x *RegisterServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servermanager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServerRequest.ProtoReflect.Descriptor instead.
func (*RegisterServerRequest) Descriptor() ([]byte, []int) {
	return file_servermanager_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterServerRequest) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

type UnregisterServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      *ServerId              `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterServerRequest) Reset() {
	*x = UnregisterServerRequest{}
	mi := &file_servermanager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterServerRequest) ProtoMessage() {}

func (x *UnregisterServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servermanager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterServerRequest.ProtoReflect.Descriptor instead.
func (*UnregisterServerRequest) Descriptor() ([]byte, []int) {
	return file_servermanager_proto_rawDescGZIP(), []int{1}
}

func (x *UnregisterServerRequest) GetServerId() *ServerId {
	if x != nil {
		return x.ServerId
	}
	return nil
}

var File_servermanager_proto protoreflect.FileDescriptor

const file_servermanager_proto_rawDesc = "" +
	"\n" +
	"\x13servermanager.proto\x12\vyggplane.v1\x1a\fcommon.proto\"D\n" +
	"\x15RegisterServerRequest\x12+\n" +
	"\x06server\x18\x01 \x01(\v2\x13.yggplane.v1.ServerR\x06server\"M\n" +
	"\x17UnregisterServerRequest\x122\n" +
	"\tserver_id\x18\x01 \x01(\v2\x15.yggplane.v1.ServerIdR\bserverId2\xc0\x01\n" +
	"\x14ServerManagerService\x12Q\n" +
	"\x0eRegisterServer\x12\".yggplane.v1.RegisterServerRequest\x1a\x17.yggplane.v1.ControlAck(\x010\x01\x12U\n" +
	"\x10UnregisterServer\x12$.yggplane.v1.UnregisterServerRequest\x1a\x17.yggplane.v1.ControlAck(\x010\x01B-Z+github.com/didopimentel/yggdrasil/api/pb;pbb\x06proto3"

var (
	file_servermanager_proto_rawDescOnce sync.Once
	file_servermanager_proto_rawDescData []byte
)

func file_servermanager_proto_rawDescGZIP() []byte {
	file_servermanager_proto_rawDescOnce.Do(func() {
		file_servermanager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_servermanager_proto_rawDesc), len(file_servermanager_proto_rawDesc)))
	})
	return file_servermanager_proto_rawDescData
}

var file_servermanager_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_servermanager_proto_goTypes = []any{
	(*RegisterServerRequest)(nil),   // 0: yggplane.v1.RegisterServerRequest
	(*UnregisterServerRequest)(nil), // 1: yggplane.v1.UnregisterServerRequest
	(*Server)(nil),                  // 2: yggplane.v1.Server
	(*ServerId)(nil),                // 3: yggplane.v1.ServerId
	(*ControlAck)(nil),              // 4: yggplane.v1.ControlAck
}
var file_servermanager_proto_depIdxs = []int32{
	2, // 0: yggplane.v1.RegisterServerRequest.server:type_name -> yggplane.v1.Server
	3, // 1: yggplane.v1.UnregisterServerRequest.server_id:type_name -> yggplane.v1.ServerId
	0, // 2: yggplane.v1.ServerManagerService.RegisterServer:input_type -> yggplane.v1.RegisterServerRequest
	1, // 3: yggplane.v1.ServerManagerService.UnregisterServer:input_type -> yggplane.v1.UnregisterServerRequest
	4, // 4: yggplane.v1.ServerManagerService.RegisterServer:output_type -> yggplane.v1.ControlAck
	4, // 5: yggplane.v1.ServerManagerService.UnregisterServer:output_type -> yggplane.v1.ControlAck
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_servermanager_proto_init() }
func file_servermanager_proto_init() {
	if File_servermanager_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_servermanager_proto_rawDesc), len(file_servermanager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_servermanager_proto_goTypes,
		DependencyIndexes: file_servermanager_proto_depIdxs,
		MessageInfos:      file_servermanager_proto_msgTypes,
	}.Build()
	File_servermanager_proto = out.File
	file_servermanager_proto_goTypes = nil
	file_servermanager_proto_depIdxs = nil
}
